### ISSUE TITLE
[Duplicate] Installation fails on SailfishOS 5.0.0

### ISSUE THREAD

**Issue by HenriVSL** [sailfishos-chum/sailfishos-chum-gui-installer#46] opened 2024-11-28 21:22 UTC
**SailfishOS VERSION** (Settings → About product → Build): 5.0.0.29
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Reeder Jolla C2
<br />**SailfishOS:Chum VERSION(s)** (`pkcon search name sailfishos-chum`):  sailfishos-chum-gui-installer-0.6.9-1.7.1.jolla.noarch
<br />

#### BUG DESCRIPTION
Installation fails. Log included.

#### ATTACH LOG-FILE

Upload the log-file from `/var/log/sailfishos-chum-gui-installer.log.txt` here.
[sailfishos-chum-gui-installer.log.txt](https://github.com/user-attachments/files/17952369/sailfishos-chum-gui-installer.log.txt)

#### ADDITIONAL INFORMATION

Could this be similar issue as with Storeman installer?
*Edit:* I.e. [Storeman Installer issue \#318](https://github.com/storeman-developers/harbour-storeman-installer/issues/318)

**Comment by Olf0** [comment] 2024-11-29 00:01
@HenriVSL, thank you for you concise issue report, even though I have to dismiss it here.

> Could this be similar issue as with Storeman installer?

No, it is not:
* The SailfishOS:Chum GUI Installer and the SailfishOS:Chum GUI application currently use the same shell code in their spec files' `%post` scriptlets as [Storeman Installer 2.2.7](https://github.com/storeman-developers/harbour-storeman-installer/releases), which was always working fine.
  <sub>I will update them to the state of Storeman Installer 2.3.0, soon™.
* The SailfishOS:Chum community repository does not yet provide a sub-repository for SailfishOS 5.0, this is why the installation of the SailfishOS:Chum GUI application fails (i.e. no repository exists to install the SailfishOS:Chum GUI application for SailfishOS 5.0 from), see https://build.sailfishos.org/project/show/sailfishos:chum

This is a duplicate of [issue \#117 for SailfishOS:Chum](https://github.com/sailfishos-chum/main/issues/117), hence I will close this one here, because it is not the SailfishOS:Chum GUI Installer's fault.

You may manually download and install the SailfishOS:Chum GUI application's RPM for the prior SailfishOS release (i.e. 4.6 for 5.0) and set the "Manual OS version override" to last point release of the prior SailfishOS release (i.e. `4.6.0.15` for 5.0).
Currently that is: https://repo.sailfishos.org/obs/sailfishos:/chum/4.6_aarch64/aarch64/sailfishos-chum-gui-0.6.9-1.10.1.jolla.aarch64.rpm

**Closed as not planned by Olf0** 2024-11-29 00:01 UTC
Labels: invalid
